const specialization = [
  'Dermatology',
  'Dentistry',
  'Psychiatry',
  'Pediatrics and New Born',
  'Neurology',
  'Orthopedics',
  'Gynaecology and Infertility',
  'Ear,Nose and Throat',
  'Cardiology and Vascular Disease',
  'Allergy abd Immunology',
  'Andrology and Male Infertility',
  'Audiology',
  'Cariology and Thoracic Surgery',
  'Chest and Respiratory',
  'Diabetes and Endocrinology',
  'Diagnostic Radiology',
  'Dietitian and Nutrition',
  'Family Medicine',
  'Gastroenterology and Endoscopy',
  'General Surgery',
  'Geriatrics',
  'Hematology',
  'Internal Medicine',
  'IVF and Infertility',
  'Laboratories',
  'Neurosurgery',
  'Obesity and Laparoscopic Surgery',
];

const arabicSpecialization = [
  'الأمراض الجلدية',
  'طب الأسنان',
  'الطب النفسي',
  'طب الأطفال وحديثي الولادة',
  'علم الأعصاب',
  'طب العظام',
  'أمراض النساء والعقم',
  'انف واذن وحنجرة',
  'أمراض القلب والأوعية الدموية',
  'أمراض الحساسية والمناعة',
  'أمراض الذكورة والعقم عند الذكور',
  'السمعيات',
  'جراحة المسالك البولية والصدر',
  'الصدر والجهاز التنفسي',
  'السكري والغدد الصماء',
  'الأشعة التشخيصية',
  'حمية وتغذية',
  'طب الأسرة',
  'أمراض الجهاز الهضمي والتنظير',
  'الجراحة العامة',
  'طب الشيخوخة',
  'أمراض الدم',
  'الطب الباطني',
  'أطفال الأنابيب والعقم',
  'مختبرات',
  'جراحة الاعصاب',
  'جراحة السمنة بالمنظار',
];

const location = [
  'Cairo',
  'Giza',
  'Alexandria',
  'North Coast',
  'Qalyubia',
  'Gharbia',
  'Menofia',
  'Fayoum',
  'El-Dakahlia',
  'El-Sharqia',
  'El-Beheira',
  'Matrouh',
  'Assuit',
  'El-Ismailia',
  'Hurghada',
  'Sharm El-Sheikh',
  'Portsaid',
  'Suez',
  'Sohag',
  'El-Minia',
  'Kafr El sheikh',
  'Luxor',
  'Qena',
  'Aswan',
  'Beni Suef',
];

export { specialization, arabicSpecialization, location };
